In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection

from sklearn.linear_model import LinearRegression
from sklearn.utils import check_random_state
from sklearn import preprocessing

# n = 100
# x = np.arange(n)
# rs = check_random_state(0)
# y = rs.randint(-50, 50, size=(n,)) + 50. * np.log1p(np.arange(n))

In [2]:
X16 = pd.read_csv('X16.csv', sep=',', header='infer') 
X16.columns

Index(['Unnamed: 0', 'parcelid', 'logerror', 'transactiondate',
       'airconditioningtypeid', 'bathroomcnt', 'bedroomcnt',
       'buildingqualitytypeid', 'calculatedbathnbr',
       'calculatedfinishedsquarefeet', 'finishedsquarefeet12', 'fips',
       'fullbathcnt', 'garagecarcnt', 'garagetotalsqft',
       'heatingorsystemtypeid', 'latitude', 'longitude', 'lotsizesquarefeet',
       'propertycountylandusecode', 'propertylandusetypeid',
       'propertyzoningdesc', 'rawcensustractandblock', 'regionidcity',
       'regionidcounty', 'regionidneighborhood', 'regionidzip', 'roomcnt',
       'unitcnt', 'yearbuilt', 'numberofstories', 'structuretaxvaluedollarcnt',
       'taxvaluedollarcnt', 'assessmentyear', 'landtaxvaluedollarcnt',
       'taxamount', 'censustractandblock'],
      dtype='object')

In [3]:
data = {
    'err': X16['logerror'].values,
    'surface': X16['calculatedfinishedsquarefeet'].values
}
X = pd.DataFrame(
    data=data,
    index=X16['parcelid'].values, 
)
print(X.count())

err        90275
surface    89614
dtype: int64


In [4]:
X.head()

err  surface
11016594  0.0276   1684.0
14366692 -0.1684   2263.0
12098116 -0.0040   2217.0
12643413  0.0218    839.0
14432541 -0.0050   2283.0

In [5]:
X.isnull().sum()

err          0
surface    661
dtype: int64

In [6]:
X.dropna(inplace=True)
X.isnull().sum()

err        0
surface    0
dtype: int64

In [7]:
X.count()

err        89614
surface    89614
dtype: int64

In [8]:
y = X.err.values
y

array([ 0.0276, -0.1684, -0.004 , ..., -0.2679,  0.0602,  0.4207])

In [9]:
x = X.surface.values.reshape(-1, 1)

In [10]:
lr = LinearRegression()
lr.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [11]:
lr.predict(x)

array([0.01096208, 0.0148289 , 0.01452169, ..., 0.01719307, 0.00662108,
       0.00989353])

In [36]:
fig = plt.figure(figsize=(15,5))
plt.plot(x, y, 'r.', markersize=0.5)
plt.plot(x, lr.predict(x), 'b-')
plt.show()

NameError: name 'nplog' is not defined

<Figure size 1080x360 with 0 Axes>

In [13]:
lr.predict([[5000]])

array([0.03310782])

### Data normalisation

In [17]:
X.head()

err  surface
11016594  0.0276   1684.0
14366692 -0.1684   2263.0
12098116 -0.0040   2217.0
12643413  0.0218    839.0
14432541 -0.0050   2283.0

In [26]:
X.surface.values.reshape(-1,1)

array([[1684.],
       [2263.],
       [2217.],
       ...,
       [2617.],
       [1034.],
       [1524.]])

In [25]:
preprocessing.normalize(X.surface.values.reshape(-1,1), norm='l2')

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])